# Generate a header of tree-sitter query strings embedded as raw string
# literals, so the highlighter has no runtime file or Qt-resource dependency.
#
#   hungryeditor_embed_queries(<output-header> NAME1 path1 [NAME2 path2 ...])
#
# Each NAME becomes `inline constexpr std::string_view <NAME>` in namespace
# hungryeditor::queries.

function(hungryeditor_embed_queries output)
    set(_body "// Generated by cmake/EmbedQueries.cmake — do not edit.\n#pragma once\n\n")
    string(APPEND _body "#include <string_view>\n\nnamespace hungryeditor::queries {\n\n")

    set(_pairs ${ARGN})
    list(LENGTH _pairs _count)
    math(EXPR _last "${_count} - 1")
    foreach(_i RANGE 0 ${_last} 2)
        list(GET _pairs ${_i} _name)
        math(EXPR _j "${_i} + 1")
        list(GET _pairs ${_j} _path)
        file(READ "${_path}" _content)
        string(APPEND _body
            "inline constexpr std::string_view ${_name} = R\"tsquery(\n${_content})tsquery\";\n\n")
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_path}")
    endforeach()

    string(APPEND _body "} // namespace hungryeditor::queries\n")

    file(GENERATE OUTPUT "${output}" CONTENT "${_body}")
endfunction()
