# Generate a header of tree-sitter query strings embedded as raw string
# literals, so the highlighter has no runtime file or Qt-resource dependency.
#
#   hungryeditor_embed_queries(<output-header>
#       "<NAME>|<path>"                 # one query file
#       "<NAME>|<path-a>|<path-b>"      # concatenated, in order
#       ...)
#
# Each NAME becomes `inline constexpr std::string_view <NAME>` in namespace
# hungryeditor::queries. Concatenation is how a dialect query that builds on
# its base language is embedded (e.g. C++ = C highlights + C++ highlights).

function(hungryeditor_embed_queries output)
    set(_body "// Generated by cmake/EmbedQueries.cmake — do not edit.\n#pragma once\n\n")
    string(APPEND _body "#include <string_view>\n\nnamespace hungryeditor::queries {\n\n")

    foreach(_entry ${ARGN})
        string(REPLACE "|" ";" _parts "${_entry}")
        list(POP_FRONT _parts _name)

        set(_content "")
        foreach(_path ${_parts})
            file(READ "${_path}" _chunk)
            string(APPEND _content "${_chunk}\n")
            set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_path}")
        endforeach()

        string(APPEND _body
            "inline constexpr std::string_view ${_name} = R\"tsquery(\n${_content})tsquery\";\n\n")
    endforeach()

    string(APPEND _body "} // namespace hungryeditor::queries\n")

    file(GENERATE OUTPUT "${output}" CONTENT "${_body}")
endfunction()
